### ISSUE TITLE
Help Gsoc2024 - Discussion

### ISSUE THREAD

**Issue by abhayguptas** [chicagopcdc/GSoC#1]
Hi, I'm Abhay! I am opening this issue to connect with the maintainers or the team members of this project. I am interested in contributing to this project under GSoC. I took a look at the list of ideas and found 2 of them that suit my background and match my skill set:

- Front-end and Adaptive Question Rendering
- Exploration of a new Component of the open-source GEN3 framework

I need some help understanding the project and taking a look around the code. It will help me create an outline for working and implementation.

Can anyone help me with this?

Thanks, Abhay 🙂

**Comment by grugna** [comment]
Please follow the instructions on the GSOC website. This is not the right place for questions.
